### PR TITLE
feature: converter text for isHtml - Sir TrevorJS v0.5

### PR DESCRIPTION
**Pull request by caouecs**
Convert text for SirTrevorJS 0.5 with isHtml support for #15

### CODE REVIEW

**Comment by Zae** [comment]
variable $data is undefined, it should be $this->data, with that change it works great.

**Comment by caouecs** [comment]
Oups, sorry.

If now, it's ok, I will change the branch 2.0

**Comment by Zae** [comment]
Yes, can you also merge it on the 1.* branch? I'm still on L4.

**Comment by caouecs** [comment]
done

**Pull request merged**
