### PR TITLE
Should use Laravel's BaseController here

### PR DESCRIPTION
**Pull request by rafaelbeckel**
Using 'App' namespace could mess up with applications using custom namespaces

### CODE REVIEW

**Comment by caouecs** [comment]
I prefer to use instead facade 'Controller', like before

**Comment by rafaelbeckel** [comment]
OK, I'm using the Facade too, pointing to my actual base Controller.

As Laravel 5 doesn't come with this Facade as default, I think it would be cool to point this out in the readme.

Or, instead of using routes and a Controller in the package, maybe it would be more "Laravel 5's" way to use a Trait that provides Tweet and Upload methods. So people would only need to "use SirTrevorJS" in their controller implementation and also they could choose their own routes.

**Comment by caouecs** [comment]
Hello @rafaelbeckel, I do a trait for controller in develop branch.

**Comment by rafaelbeckel** [comment]
Wow, that's cool!!

I'll test it when I have some time to study it carefully and maybe integrate to my project.

As ST is a core feature of the project I'm working, I ended up using my fork because I needed some very custom features (adding a user hash id to directory upload, for example).

I have a checklist of some changes that I intended to do with my fork, that I think it would be a bit simpler to use, but haven't found time yet to focus on this (just now my focus is the project that just **uses** ST). 

If you'd like, I could share this checklist here as issues, so we can talk about them before actually implementing, and then I would pull the changes here, instead of into my own fork.

**Comment by caouecs** [comment]
Yes, with pleasure

**Pull request closed without merging**
